// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Authorization authorization
//
// swagger:model Authorization
type Authorization struct {

	// id
	ID string `json:"id,omitempty"`

	// requesting party
	// Required: true
	RequestingParty *string `json:"requestingParty"`

	// scope
	// Required: true
	Scope *AuthorizationScope `json:"scope"`

	// zcap
	Zcap interface{} `json:"zcap,omitempty"`
}

// Validate validates this authorization
func (m *Authorization) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequestingParty(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Authorization) validateRequestingParty(formats strfmt.Registry) error {

	if err := validate.Required("requestingParty", "body", m.RequestingParty); err != nil {
		return err
	}

	return nil
}

func (m *Authorization) validateScope(formats strfmt.Registry) error {

	if err := validate.Required("scope", "body", m.Scope); err != nil {
		return err
	}

	if m.Scope != nil {
		if err := m.Scope.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scope")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this authorization based on the context it is used
func (m *Authorization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Authorization) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if m.Scope != nil {
		if err := m.Scope.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("scope")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Authorization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Authorization) UnmarshalBinary(b []byte) error {
	var res Authorization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// AuthorizationScope authorization scope
//
// swagger:model AuthorizationScope
type AuthorizationScope struct {

	// action
	// Required: true
	Action []string `json:"action"`

	// caveats
	Caveats []*Caveat `json:"caveats"`

	// resource ID
	ResourceID string `json:"resourceID,omitempty"`

	// resource type
	ResourceType string `json:"resourceType,omitempty"`
}

// Validate validates this authorization scope
func (m *AuthorizationScope) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCaveats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var authorizationScopeActionItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["read","reference"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		authorizationScopeActionItemsEnum = append(authorizationScopeActionItemsEnum, v)
	}
}

func (m *AuthorizationScope) validateActionItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, authorizationScopeActionItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AuthorizationScope) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("scope"+"."+"action", "body", m.Action); err != nil {
		return err
	}

	for i := 0; i < len(m.Action); i++ {

		// value enum
		if err := m.validateActionItemsEnum("scope"+"."+"action"+"."+strconv.Itoa(i), "body", m.Action[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *AuthorizationScope) validateCaveats(formats strfmt.Registry) error {
	if swag.IsZero(m.Caveats) { // not required
		return nil
	}

	for i := 0; i < len(m.Caveats); i++ {
		if swag.IsZero(m.Caveats[i]) { // not required
			continue
		}

		if m.Caveats[i] != nil {
			if err := m.Caveats[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("scope" + "." + "caveats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this authorization scope based on the context it is used
func (m *AuthorizationScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCaveats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthorizationScope) contextValidateCaveats(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Caveats); i++ {

		if m.Caveats[i] != nil {
			if err := m.Caveats[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("scope" + "." + "caveats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthorizationScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthorizationScope) UnmarshalBinary(b []byte) error {
	var res AuthorizationScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
