// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Caveat caveat
//
// swagger:model Caveat
type Caveat struct {

	// type
	// Enum: [expiry]
	Type string `json:"type,omitempty"`
}

// Validate validates this caveat
func (m *Caveat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var caveatTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["expiry"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		caveatTypeTypePropEnum = append(caveatTypeTypePropEnum, v)
	}
}

const (

	// CaveatTypeExpiry captures enum value "expiry"
	CaveatTypeExpiry string = "expiry"
)

// prop value enum
func (m *Caveat) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, caveatTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Caveat) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this caveat based on context it is used
func (m *Caveat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Caveat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Caveat) UnmarshalBinary(b []byte) error {
	var res Caveat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
