#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

@all
@governance_rest
Feature: Governance VC REST API

  Scenario Outline: Governance APIs
    Given Governance Profile "<profile>" is created with DID "<did>", privateKey "<privateKey>", keyID "<keyID>", signatureHolder "<signatureHolder>", uniRegistrar '<uniRegistrar>', didMethod "<didMethod>", signatureType "<signatureType>" and keyType "<keyType>"
    Then  Governance "<profile>" generates credential with signatureType "<signatureType>"
    Examples:
      | profile                        | did                                                              | privateKey                                                                               | keyID                                                                                                           | signatureHolder |uniRegistrar                                                                                                                                                      |  didMethod      |    signatureType      |  keyType  |
      |governance_unireg_ed25519_pv    |                                                                  |                                                                                          |                                                                                                                 | ProofValue      |{"driverURL":"http://uni-registrar-web:9080/1.0/register?driverId=driver-did-method-rest"}                                                              		  | did:trustbloc   | Ed25519Signature2018  |  Ed25519  |
      |governance_unireg_p256_jws      |                                                                  |                                                                                          |                                                                                                                 | JWS             |{"driverURL":"http://uni-registrar-web:9080/1.0/register?driverId=driver-did-method-rest"}                                                              		  | did:trustbloc   | JsonWebSignature2020  |  P256     |
      |governance_local_ed25519_jws    |                                                                  |                                                                                          |                                                                                                                 | JWS             |                                                                                                                                                                  | did:trustbloc   | Ed25519Signature2018  |  Ed25519  |
      |governance_local_p256_pv        |                                                                  |                                                                                          |                                                                                                                 | ProofValue      |                                                                                                                                                                  | did:trustbloc   | JsonWebSignature2020  |  P256     |
      |governance_unireg_ed25519       |                                                                  |                                                                                          |                                                                                                                 | JWS             |{"driverURL":"http://uni-registrar-web:9080/1.0/register?driverId=driver-did-method-rest"}                                                              		  | did:trustbloc   | JsonWebSignature2020  |  Ed25519  |
      |governance_unireg_p256          |                                                                  |                                                                                          |                                                                                                                 | JWS             |{"driverURL":"http://uni-registrar-web:9080/1.0/register?driverId=driver-did-method-rest"}                                                              		  | did:trustbloc   | JsonWebSignature2020  |  P256     |
