# Copyright SecureKey Technologies Inc.
#
# SPDX-License-Identifier: Apache-2.0

openapi: 3.0.0
info:
  title: Confidential Storage Hub
  description: Confidential Storage Hub
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  /profiles:
    post:
      description: Create new account.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        201:
          description: Create a new account.
          headers:
            Location:
              description: Location of the new Account.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
  /profiles/{profileID}/queries:
    post:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/DocQuery"
      responses:
        201:
          description: TODO
          headers:
            Location:
              description: TODO
              schema:
                type: string
  /profiles/{profileID}/authorizations:
    post:
      description: TODO
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Authorization"
      responses:
        201:
          description: TODO
          headers:
            Location:
              description: TODO
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Authorization"
  /compare:
    post:
      description: Evaluates an operator with its inputs and returns the result.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ComparisonRequest"
      responses:
        200:
          description: TODO
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Comparison"
  /extract:
    get:
      description: extracts the contents of a document. TODO - request schema
      parameters:
        - in: query
          name: resource
          schema:
            type: string
      responses:
        200:
          description: The extracted and decrypted object.
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        controller:
          type: string
        zcap:
          type: string
    ComparisonRequest:
      type: object
      properties:
        op:
          $ref: "#/components/schemas/Operator"
    Comparison:
      description: TODO - "comparison" does not sound apt as a name
      type: object
      properties:
        result:
          type: boolean
    Operator:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - eq
    EqOp:
      allOf:
        - $ref: "#/components/schemas/Operator"
        - type: object
          required:
            - args
          properties:
            args:
              type: array
              items:
                $ref: "#/components/schemas/Query"
              minItems: 2
    Query:
      type: object
      required:
        - type
        - upstreamAuth
      properties:
        id:
          type: string
        type:
          type: string
          enum:
            - doc
            - ref
    DocQuery:
      allOf:
        - $ref: "#/components/schemas/Query"
        - type: object
          required:
            - vaultID
            - docID
            - upstreamAuth
          properties:
            vaultID:
              type: string
            docID:
              type: string
            path:
              type: string
            upstreamAuth:
              type: object
              required:
                - edv
                - kms
              properties:
                edv:
                  $ref: "#/components/schemas/UpstreamAuthorization"
                kms:
                  $ref: "#/components/schemas/UpstreamAuthorization"
    RefQuery:
      allOf:
        - $ref: "#/components/schemas/Query"
        - type: object
          required:
            - ref
          properties:
            ref:
              type: string
    Authorization:
      type: object
      required:
        - queryID
        - requestingParty
        - scope
      properties:
        id:
          type: string
        requestingParty:
          type: string
        scope:
          type: object
          required:
            - resource
            - action
          properties:
            resourceID:
              type: string
            resourceType:
              type: string
            action:
              type: array
              items:
                type: string
                enum:
                  - read
                  - reference
            caveats:
              type: array
              items:
                $ref: "#/components/schemas/Caveat"
        zcap:
          type: object
    UpstreamAuthorization:
      type: object
      properties:
        baseURL:
          type: string
        zcap:
          type: string
    Caveat:
      type: object
      properties:
        type:
          type: string
          enum:
            - expiry
    ExpiryCaveat:
      allOf:
        - $ref: "#/components/schemas/Caveat"
        - type: object
          properties:
            duration:
              type: integer
              description: Duration (in seconds) for which this authorization will remain valid.
