// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for DIDMethod.
const (
	DIDMethodKey DIDMethod = "key"
	DIDMethodOrb DIDMethod = "orb"
	DIDMethodWeb DIDMethod = "web"
)

// Defines values for KMSConfigType.
const (
	KMSConfigTypeAws   KMSConfigType = "aws"
	KMSConfigTypeLocal KMSConfigType = "local"
	KMSConfigTypeWeb   KMSConfigType = "web"
)

// Defines values for VCFormat.
const (
	JwtVcJson   VCFormat = "jwt_vc_json"
	JwtVcJsonLd VCFormat = "jwt_vc_json-ld"
	LdpVc       VCFormat = "ldp_vc"
)

// Defines values for VPFormat.
const (
	JwtVp VPFormat = "jwt_vp"
	LdpVp VPFormat = "ldp_vp"
)

// Model to convey the details about the Credentials the Client wants to obtain.
type AuthorizationDetails struct {
	// String representing a format in which the Credential is requested to be issued. Valid values defined by OIDC4VC are jwt_vc_json-ld and ldp_vc. Issuer can refuse the authorization request if the given credential type and format combo is not supported.
	Format *string `json:"format,omitempty"`

	// An array of strings that allows a client to specify the location of the resource server(s) allowing the Authorization Server to mint audience restricted access tokens.
	Locations *[]string `json:"locations,omitempty"`

	// String that determines the authorization details type. MUST be set to "openid_credential" for OIDC4VC.
	Type string `json:"type"`

	// String array denoting the types of the requested Credential.
	Types []string `json:"types"`
}

// DID method of the DID to be used for signing.
type DIDMethod string

// Model for KMS configuration.
type KMSConfig struct {
	// Prefix of database used by local kms.
	DbPrefix *string `json:"dbPrefix,omitempty"`

	// Type of database used by local kms.
	DbType *string `json:"dbType,omitempty"`

	// URL to database used by local kms.
	DbURL *string `json:"dbURL,omitempty"`

	// KMS endpoint.
	Endpoint *string `json:"endpoint,omitempty"`

	// Path to secret lock used by local kms.
	SecretLockKeyPath *string `json:"secretLockKeyPath,omitempty"`

	// Type of kms used to create and store DID keys.
	Type KMSConfigType `json:"type"`
}

// Type of kms used to create and store DID keys.
type KMSConfigType string

// Supported VC formats.
type VCFormat string

// Supported VP formats.
type VPFormat string

// WalletInitiatedFlowData defines model for WalletInitiatedFlowData.
type WalletInitiatedFlowData struct {
	ClaimEndpoint        string   `json:"claim_endpoint"`
	CredentialTemplateId string   `json:"credential_template_id"`
	OpState              string   `json:"op_state"`
	ProfileId            string   `json:"profile_id"`
	ProfileVersion       string   `json:"profile_version"`
	Scopes               []string `json:"scopes"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5xWUW/bOAz+K4SeNsBNi9s95a3nbEDQ9hYsa/ZwGwJZomM1suST6KS5of/9QDlu0sYZ",
	"tr0EsSR+/Eh+IvVdKF833qGjKMbfRVQV1jL9vW6p8sH8J8l4N0GSxqZ1jVEF0/CqGIs7r9ECeVDebXAH",
	"VCHo7jDIwreUVvKAGh0ZaWP3bQ06gq10FNnYFySNG4lMNME3GMhg8lX6UEs69TqnYNwKAjYBIwO7FUjo",
	"ToNxsK2Mql55BhMh4L8tRkLNTgsEE2OLegQLaY2GjbQtRtBYGocaih18nE7yPxc5yIDwsKXlRi0foncX",
	"VoN0Gqxulhs1ginDBFDSQcCyjZhcy+ME9q7BlGlzZTboQB3Y0a7BBLqPQvm68MzZeYLYNo0PhJpTxCfF",
	"WMSUA/GUCetV8jFQnmsHMgS5A19CZ8AFkATSWr+NIEF1pSAPsUFlyq6EPSTb8XfA6NugECKGDYY38W2H",
	"wInn/RdigXk6xJi1cQSy1QadSigUjOL8S6Uwcu3X6CJHZQjrFMBJePuFFMfh+4wkUnAaCUNtHMaBQvTq",
	"ZJgR3N3PP7MSIqYcfBW+QWf08lCZr4JL0kthsAC8EM9S6gqg0Xnq05UMDrntRXkQ669k5CkTDGECajH+",
	"p9vsOX3LBBmyfHrwPj9j+eIBFTH4ZDq5Q6q8Pg1oMp1AnfZ67rzSXaU2YtIuRLNyxq04AnRtzZR8KEQm",
	"tsi/a9wlVq9jurmb596VZnWuxzD2zd2cG01pVm1IcZy2DF3MApbm8RSmW2fmWpIsZNyTLnZJ7hbWdRws",
	"ry4+D0qOV38L7v7T7Sna/adbTuUvgqHTjTduoEdyrvrdQdOIKiDderW+wd1MUjWQMklVag3pKFNZ/yQv",
	"+mHG1nXscHhwBJTUtb5IPnSaWuMuHisoOXvWkNzGAQ0N3YMj/R8E9lr0mXi8ILmKbJUmQhDfnjKxyD+c",
	"Gz99O4ZFvu/XL9i+HBUiO14QmejGxjG3Z1cDmVzMfoLG7CyNpnfYvHA4O+/wi7QWaeoMGUmoP1i/nUiS",
	"7N+11sqCESi0+PrqKStNvTxW5An2oa0uCevGSsKl0YNHfbOMJAkHN5vgS2PP2vbbGwwx5WrgTFR+37V/",
	"s9EecTj1+IyfvU7L2SQchXxUqXPVOOncTM+40g/cutBG+st6BYt83r8ljt8eLHrJA5ov4QaDKc1+/LeR",
	"R9aXdzks8ovr2RSk9W4FW0MVfGzQTSf8PGqCJ69816O7G3SZYDCAcYRBqoSWzLqAWKfWKHQxFdjJOs2o",
	"RqoKL/4YXYlMtMGKsaiImji+vNxutyOZtkc+rC73tvHydpq//3v+nm1G9JgmWJ+63Ne1d/thy9QWKTQW",
	"8PG7kF8rRiG8WeTztyITz6IRVyNmkrSITjZGjMW70VUi10iqohjzhXj6PwAA///9djyXRQsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
