// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExtractResp extract resp
//
// swagger:model ExtractResp
type ExtractResp struct {

	// documents
	// Required: true
	Documents []interface{} `json:"documents"`
}

// Validate validates this extract resp
func (m *ExtractResp) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocuments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExtractResp) validateDocuments(formats strfmt.Registry) error {

	if err := validate.Required("documents", "body", m.Documents); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this extract resp based on context it is used
func (m *ExtractResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExtractResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExtractResp) UnmarshalBinary(b []byte) error {
	var res ExtractResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
