// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"io/ioutil"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// Operator Operators indicate the kind of comparison operation to be performed.
//
//
// swagger:discriminated Operator type
type Operator interface {
	runtime.Validatable
	runtime.ContextValidatable

	// type
	// Required: true
	Type() string
	SetType(string)

	// AdditionalProperties in base type shoud be handled just like regular properties
	// At this moment, the base type property is pushed down to the subtype
}

type operator struct {
	typeField string
}

// Type gets the type of this polymorphic type
func (m *operator) Type() string {
	return "Operator"
}

// SetType sets the type of this polymorphic type
func (m *operator) SetType(val string) {
}

// UnmarshalOperatorSlice unmarshals polymorphic slices of Operator
func UnmarshalOperatorSlice(reader io.Reader, consumer runtime.Consumer) ([]Operator, error) {
	var elements []json.RawMessage
	if err := consumer.Consume(reader, &elements); err != nil {
		return nil, err
	}

	var result []Operator
	for _, element := range elements {
		obj, err := unmarshalOperator(element, consumer)
		if err != nil {
			return nil, err
		}
		result = append(result, obj)
	}
	return result, nil
}

// UnmarshalOperator unmarshals polymorphic Operator
func UnmarshalOperator(reader io.Reader, consumer runtime.Consumer) (Operator, error) {
	// we need to read this twice, so first into a buffer
	data, err := ioutil.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	return unmarshalOperator(data, consumer)
}

func unmarshalOperator(data []byte, consumer runtime.Consumer) (Operator, error) {
	buf := bytes.NewBuffer(data)
	buf2 := bytes.NewBuffer(data)

	// the first time this is read is to fetch the value of the type property.
	var getType struct {
		Type string `json:"type"`
	}
	if err := consumer.Consume(buf, &getType); err != nil {
		return nil, err
	}

	if err := validate.RequiredString("type", "body", getType.Type); err != nil {
		return nil, err
	}

	// The value of type is used to determine which type to create and unmarshal the data into
	switch getType.Type {
	case "EqOp":
		var result EqOp
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	case "Operator":
		var result operator
		if err := consumer.Consume(buf2, &result); err != nil {
			return nil, err
		}
		return &result, nil
	}
	return nil, errors.New(422, "invalid type value: %q", getType.Type)
}

// Validate validates this operator
func (m *operator) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this operator based on context it is used
func (m *operator) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
