// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/edge-service/pkg/client/comparator/models"
)

// NewPostAuthorizationsParams creates a new PostAuthorizationsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAuthorizationsParams() *PostAuthorizationsParams {
	return &PostAuthorizationsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAuthorizationsParamsWithTimeout creates a new PostAuthorizationsParams object
// with the ability to set a timeout on a request.
func NewPostAuthorizationsParamsWithTimeout(timeout time.Duration) *PostAuthorizationsParams {
	return &PostAuthorizationsParams{
		timeout: timeout,
	}
}

// NewPostAuthorizationsParamsWithContext creates a new PostAuthorizationsParams object
// with the ability to set a context for a request.
func NewPostAuthorizationsParamsWithContext(ctx context.Context) *PostAuthorizationsParams {
	return &PostAuthorizationsParams{
		Context: ctx,
	}
}

// NewPostAuthorizationsParamsWithHTTPClient creates a new PostAuthorizationsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAuthorizationsParamsWithHTTPClient(client *http.Client) *PostAuthorizationsParams {
	return &PostAuthorizationsParams{
		HTTPClient: client,
	}
}

/* PostAuthorizationsParams contains all the parameters to send to the API endpoint
   for the post authorizations operation.

   Typically these are written to a http.Request.
*/
type PostAuthorizationsParams struct {

	// Authorization.
	Authorization *models.Authorization

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post authorizations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthorizationsParams) WithDefaults() *PostAuthorizationsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post authorizations params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAuthorizationsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post authorizations params
func (o *PostAuthorizationsParams) WithTimeout(timeout time.Duration) *PostAuthorizationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post authorizations params
func (o *PostAuthorizationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post authorizations params
func (o *PostAuthorizationsParams) WithContext(ctx context.Context) *PostAuthorizationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post authorizations params
func (o *PostAuthorizationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post authorizations params
func (o *PostAuthorizationsParams) WithHTTPClient(client *http.Client) *PostAuthorizationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post authorizations params
func (o *PostAuthorizationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post authorizations params
func (o *PostAuthorizationsParams) WithAuthorization(authorization *models.Authorization) *PostAuthorizationsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post authorizations params
func (o *PostAuthorizationsParams) SetAuthorization(authorization *models.Authorization) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *PostAuthorizationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Authorization != nil {
		if err := r.SetBodyParam(o.Authorization); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
