// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/edge-service/pkg/client/comparator/models"
)

// PostExtractReader is a Reader for the PostExtract structure.
type PostExtractReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostExtractReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostExtractOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostExtractInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostExtractOK creates a PostExtractOK with default headers values
func NewPostExtractOK() *PostExtractOK {
	return &PostExtractOK{}
}

/* PostExtractOK describes a response with status code 200, with default header values.

list of extracted documents
*/
type PostExtractOK struct {
	Payload *models.ExtractResp
}

func (o *PostExtractOK) Error() string {
	return fmt.Sprintf("[POST /extract][%d] postExtractOK  %+v", 200, o.Payload)
}
func (o *PostExtractOK) GetPayload() *models.ExtractResp {
	return o.Payload
}

func (o *PostExtractOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ExtractResp)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostExtractInternalServerError creates a PostExtractInternalServerError with default headers values
func NewPostExtractInternalServerError() *PostExtractInternalServerError {
	return &PostExtractInternalServerError{}
}

/* PostExtractInternalServerError describes a response with status code 500, with default header values.

Generic Error
*/
type PostExtractInternalServerError struct {
	Payload *models.Error
}

func (o *PostExtractInternalServerError) Error() string {
	return fmt.Sprintf("[POST /extract][%d] postExtractInternalServerError  %+v", 500, o.Payload)
}
func (o *PostExtractInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostExtractInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
