// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/edge-service/pkg/client/comparator/models"
)

// PostAuthorizationsReader is a Reader for the PostAuthorizations structure.
type PostAuthorizationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAuthorizationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAuthorizationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostAuthorizationsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAuthorizationsOK creates a PostAuthorizationsOK with default headers values
func NewPostAuthorizationsOK() *PostAuthorizationsOK {
	return &PostAuthorizationsOK{}
}

/* PostAuthorizationsOK describes a response with status code 200, with default header values.

Authorization created.
*/
type PostAuthorizationsOK struct {

	/* Location of the Authorization.
	 */
	Location string

	Payload *models.Authorization
}

func (o *PostAuthorizationsOK) Error() string {
	return fmt.Sprintf("[POST /authorizations][%d] postAuthorizationsOK  %+v", 200, o.Payload)
}
func (o *PostAuthorizationsOK) GetPayload() *models.Authorization {
	return o.Payload
}

func (o *PostAuthorizationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	o.Payload = new(models.Authorization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAuthorizationsInternalServerError creates a PostAuthorizationsInternalServerError with default headers values
func NewPostAuthorizationsInternalServerError() *PostAuthorizationsInternalServerError {
	return &PostAuthorizationsInternalServerError{}
}

/* PostAuthorizationsInternalServerError describes a response with status code 500, with default header values.

Generic Error
*/
type PostAuthorizationsInternalServerError struct {
	Payload *models.Error
}

func (o *PostAuthorizationsInternalServerError) Error() string {
	return fmt.Sprintf("[POST /authorizations][%d] postAuthorizationsInternalServerError  %+v", 500, o.Payload)
}
func (o *PostAuthorizationsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAuthorizationsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
