// Code generated by go-swagger; DO NOT EDIT.

// /*
// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
// */
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetExtractReader is a Reader for the GetExtract structure.
type GetExtractReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetExtractReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetExtractOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetExtractInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetExtractOK creates a GetExtractOK with default headers values
func NewGetExtractOK() *GetExtractOK {
	return &GetExtractOK{}
}

/* GetExtractOK describes a response with status code 200, with default header values.

The extracted and decrypted object.
*/
type GetExtractOK struct {
	Payload interface{}
}

func (o *GetExtractOK) Error() string {
	return fmt.Sprintf("[GET /extract][%d] getExtractOK  %+v", 200, o.Payload)
}
func (o *GetExtractOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetExtractOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetExtractInternalServerError creates a GetExtractInternalServerError with default headers values
func NewGetExtractInternalServerError() *GetExtractInternalServerError {
	return &GetExtractInternalServerError{}
}

/* GetExtractInternalServerError describes a response with status code 500, with default header values.

GetExtractInternalServerError get extract internal server error
*/
type GetExtractInternalServerError struct {
}

func (o *GetExtractInternalServerError) Error() string {
	return fmt.Sprintf("[GET /extract][%d] getExtractInternalServerError ", 500)
}

func (o *GetExtractInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
