// Code generated by go-swagger; DO NOT EDIT.

// /*
// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
// */
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetExtractParams creates a new GetExtractParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetExtractParams() *GetExtractParams {
	return &GetExtractParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetExtractParamsWithTimeout creates a new GetExtractParams object
// with the ability to set a timeout on a request.
func NewGetExtractParamsWithTimeout(timeout time.Duration) *GetExtractParams {
	return &GetExtractParams{
		timeout: timeout,
	}
}

// NewGetExtractParamsWithContext creates a new GetExtractParams object
// with the ability to set a context for a request.
func NewGetExtractParamsWithContext(ctx context.Context) *GetExtractParams {
	return &GetExtractParams{
		Context: ctx,
	}
}

// NewGetExtractParamsWithHTTPClient creates a new GetExtractParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetExtractParamsWithHTTPClient(client *http.Client) *GetExtractParams {
	return &GetExtractParams{
		HTTPClient: client,
	}
}

/* GetExtractParams contains all the parameters to send to the API endpoint
   for the get extract operation.

   Typically these are written to a http.Request.
*/
type GetExtractParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get extract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExtractParams) WithDefaults() *GetExtractParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get extract params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetExtractParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get extract params
func (o *GetExtractParams) WithTimeout(timeout time.Duration) *GetExtractParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get extract params
func (o *GetExtractParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get extract params
func (o *GetExtractParams) WithContext(ctx context.Context) *GetExtractParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get extract params
func (o *GetExtractParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get extract params
func (o *GetExtractParams) WithHTTPClient(client *http.Client) *GetExtractParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get extract params
func (o *GetExtractParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetExtractParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
