// Code generated by go-swagger; DO NOT EDIT.

// /*
// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
// */
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/edge-service/pkg/client/csh/models"
)

// PostHubstoreProfilesReader is a Reader for the PostHubstoreProfiles structure.
type PostHubstoreProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostHubstoreProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostHubstoreProfilesCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostHubstoreProfilesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostHubstoreProfilesCreated creates a PostHubstoreProfilesCreated with default headers values
func NewPostHubstoreProfilesCreated() *PostHubstoreProfilesCreated {
	return &PostHubstoreProfilesCreated{}
}

/* PostHubstoreProfilesCreated describes a response with status code 201, with default header values.

New profile.
*/
type PostHubstoreProfilesCreated struct {

	/* Location of the new Profile.
	 */
	Location string

	Payload *models.Profile
}

func (o *PostHubstoreProfilesCreated) Error() string {
	return fmt.Sprintf("[POST /hubstore/profiles][%d] postHubstoreProfilesCreated  %+v", 201, o.Payload)
}
func (o *PostHubstoreProfilesCreated) GetPayload() *models.Profile {
	return o.Payload
}

func (o *PostHubstoreProfilesCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	o.Payload = new(models.Profile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostHubstoreProfilesInternalServerError creates a PostHubstoreProfilesInternalServerError with default headers values
func NewPostHubstoreProfilesInternalServerError() *PostHubstoreProfilesInternalServerError {
	return &PostHubstoreProfilesInternalServerError{}
}

/* PostHubstoreProfilesInternalServerError describes a response with status code 500, with default header values.

Generic Error
*/
type PostHubstoreProfilesInternalServerError struct {
	Payload *models.Error
}

func (o *PostHubstoreProfilesInternalServerError) Error() string {
	return fmt.Sprintf("[POST /hubstore/profiles][%d] postHubstoreProfilesInternalServerError  %+v", 500, o.Payload)
}
func (o *PostHubstoreProfilesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostHubstoreProfilesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
