// Code generated by go-swagger; DO NOT EDIT.

// /*
// Copyright SecureKey Technologies Inc. All Rights Reserved.
//
// SPDX-License-Identifier: Apache-2.0
// */
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/trustbloc/edge-service/pkg/client/csh/models"
)

// NewPostHubstoreProfilesProfileIDQueriesParams creates a new PostHubstoreProfilesProfileIDQueriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostHubstoreProfilesProfileIDQueriesParams() *PostHubstoreProfilesProfileIDQueriesParams {
	return &PostHubstoreProfilesProfileIDQueriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostHubstoreProfilesProfileIDQueriesParamsWithTimeout creates a new PostHubstoreProfilesProfileIDQueriesParams object
// with the ability to set a timeout on a request.
func NewPostHubstoreProfilesProfileIDQueriesParamsWithTimeout(timeout time.Duration) *PostHubstoreProfilesProfileIDQueriesParams {
	return &PostHubstoreProfilesProfileIDQueriesParams{
		timeout: timeout,
	}
}

// NewPostHubstoreProfilesProfileIDQueriesParamsWithContext creates a new PostHubstoreProfilesProfileIDQueriesParams object
// with the ability to set a context for a request.
func NewPostHubstoreProfilesProfileIDQueriesParamsWithContext(ctx context.Context) *PostHubstoreProfilesProfileIDQueriesParams {
	return &PostHubstoreProfilesProfileIDQueriesParams{
		Context: ctx,
	}
}

// NewPostHubstoreProfilesProfileIDQueriesParamsWithHTTPClient creates a new PostHubstoreProfilesProfileIDQueriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostHubstoreProfilesProfileIDQueriesParamsWithHTTPClient(client *http.Client) *PostHubstoreProfilesProfileIDQueriesParams {
	return &PostHubstoreProfilesProfileIDQueriesParams{
		HTTPClient: client,
	}
}

/* PostHubstoreProfilesProfileIDQueriesParams contains all the parameters to send to the API endpoint
   for the post hubstore profiles profile ID queries operation.

   Typically these are written to a http.Request.
*/
type PostHubstoreProfilesProfileIDQueriesParams struct {

	/* ProfileID.

	   The profile's ID.
	*/
	ProfileID string

	// Request.
	Request models.Query

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post hubstore profiles profile ID queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithDefaults() *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post hubstore profiles profile ID queries params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithTimeout(timeout time.Duration) *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithContext(ctx context.Context) *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithHTTPClient(client *http.Client) *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProfileID adds the profileID to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithProfileID(profileID string) *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetProfileID(profileID)
	return o
}

// SetProfileID adds the profileId to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetProfileID(profileID string) {
	o.ProfileID = profileID
}

// WithRequest adds the request to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) WithRequest(request models.Query) *PostHubstoreProfilesProfileIDQueriesParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post hubstore profiles profile ID queries params
func (o *PostHubstoreProfilesProfileIDQueriesParams) SetRequest(request models.Query) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostHubstoreProfilesProfileIDQueriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param profileID
	if err := r.SetPathParam("profileID", o.ProfileID); err != nil {
		return err
	}
	if err := r.SetBodyParam(o.Request); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
